import { getSupabaseServer } from 'lib/supabaseServer';
function clean(v){return typeof v==='string'?v.trim():''}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const db=getSupabaseServer();if(!db)return res.status(503).json({error:'Database is not configured. Add Supabase environment variables.'});try{
 const auth=req.headers.authorization||'';let userId=null;if(auth.startsWith('Bearer ')){const token=auth.slice(7);const {data,error}=await db.auth.getUser(token);if(error) return res.status(401).json({error:'Invalid session'});userId=data.user?.id||null;}
 const {customer,items,paymentMethod='cod',couponCode=''}=req.body||{};if(!customer||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Customer details and cart items are required'});
 const phone=clean(customer.phone).replace(/\D/g,'');if(!/^[6-9]\d{9}$/.test(phone))return res.status(400).json({error:'Invalid mobile number'});if(!/^\d{6}$/.test(clean(customer.pincode)))return res.status(400).json({error:'Invalid PIN code'});
 const ids=items.map(i=>i.id);const {data:products,error:pErr}=await db.from('products').select('id,name,price,stock,active').in('id',ids);if(pErr)throw pErr;const map=new Map((products||[]).map(p=>[p.id,p]));let subtotal=0;const rows=[];for(const item of items){const p=map.get(item.id);const qty=Math.floor(Number(item.quantity));if(!p||!p.active||qty<1) return res.status(400).json({error:`Product ${item.id} is unavailable`});if(p.stock<qty)return res.status(400).json({error:`Only ${p.stock} units available for ${p.name}`});const line=Number(p.price)*qty;subtotal+=line;rows.push({product_id:p.id,product_name:p.name,quantity:qty,unit_price:p.price,line_total:line});}
 let discount=0;let coupon=null;if(couponCode){const {data:c}=await db.from('coupons').select('*').eq('code',clean(couponCode).toUpperCase()).eq('active',true).maybeSingle();if(c&&subtotal>=Number(c.min_order)&&(!c.expires_at||new Date(c.expires_at)>new Date())){coupon=c;discount=c.type==='percent'?subtotal*Number(c.value)/100:Number(c.value);if(c.max_discount)discount=Math.min(discount,Number(c.max_discount));discount=Math.min(discount,subtotal);}}
 const shipping=subtotal-discount>=1999?0:79;const total=Math.max(0,subtotal+shipping-discount);const orderNumber=`SHV-${Date.now().toString().slice(-8)}`;
 const {data:order,error:oErr}=await db.from('orders').insert({order_number:orderNumber,user_id:userId,customer_name:clean(customer.name),phone,email:clean(customer.email)||null,address:clean(customer.address),landmark:clean(customer.landmark),city:clean(customer.city),state:clean(customer.state),pincode:clean(customer.pincode),subtotal,shipping,discount,total,payment_method:paymentMethod==='prepaid'?'online':'cod',payment_status:'pending',status:'pending',coupon_code:coupon?.code||null}).select('*').single();if(oErr)throw oErr;
 const {error:iErr}=await db.from('order_items').insert(rows.map(x=>({...x,order_id:order.id})));if(iErr){await db.from('orders').delete().eq('id',order.id);throw iErr;}
 for(const row of rows){const p=map.get(row.product_id);await db.from('products').update({stock:p.stock-row.quantity}).eq('id',p.id).eq('stock',p.stock);}
 return res.status(201).json({order:{...order,items:rows}});
}catch(e){console.error(e);return res.status(500).json({error:e.message||'Could not create order'});}}
