-- SHIFAVEDA production schema. Run in Supabase SQL Editor.
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text, phone text, role text not null default 'customer' check(role in ('customer','admin')), created_at timestamptz not null default now());
create table if not exists public.products (id text primary key, name text not null, slug text unique not null, price numeric(12,2) not null default 0, mrp numeric(12,2), stock integer not null default 0, active boolean not null default true, image text, description text, category text, created_at timestamptz not null default now());
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), order_number text unique not null, user_id uuid references public.profiles(id) on delete set null, customer_name text not null, phone text not null, email text, address text not null, landmark text, city text not null, state text not null, pincode text not null, subtotal numeric(12,2) not null, shipping numeric(12,2) not null default 0, discount numeric(12,2) not null default 0, total numeric(12,2) not null, payment_method text not null default 'cod', payment_status text not null default 'pending', status text not null default 'pending', coupon_code text, created_at timestamptz not null default now());
create table if not exists public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id text not null references public.products(id), product_name text not null, quantity integer not null check(quantity > 0), unit_price numeric(12,2) not null, line_total numeric(12,2) not null);
create table if not exists public.reviews (id uuid primary key default gen_random_uuid(), product_id text not null references public.products(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, rating integer not null check(rating between 1 and 5), title text, body text not null, approved boolean not null default false, created_at timestamptz not null default now(), unique(product_id,user_id));
create table if not exists public.wishlist (user_id uuid not null references public.profiles(id) on delete cascade, product_id text not null references public.products(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,product_id));
create table if not exists public.addresses (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, name text not null, phone text not null, address text not null, landmark text, city text not null, state text not null, pincode text not null, created_at timestamptz not null default now());
create table if not exists public.coupons (code text primary key, type text not null check(type in ('percent','flat')), value numeric(12,2) not null, min_order numeric(12,2) not null default 0, max_discount numeric(12,2), active boolean not null default true, starts_at timestamptz, expires_at timestamptz, usage_limit integer, used_count integer not null default 0);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,name,phone) values(new.id,new.raw_user_meta_data->>'name',new.raw_user_meta_data->>'phone') on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security; alter table public.products enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.reviews enable row level security; alter table public.wishlist enable row level security; alter table public.addresses enable row level security; alter table public.coupons enable row level security;

drop policy if exists profiles_self on public.profiles; create policy profiles_self on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists products_public_read on public.products; create policy products_public_read on public.products for select using(active=true or exists(select 1 from profiles where id=auth.uid() and role='admin'));
drop policy if exists orders_self_read on public.orders; create policy orders_self_read on public.orders for select using(auth.uid()=user_id or exists(select 1 from profiles where id=auth.uid() and role='admin'));
drop policy if exists order_items_self_read on public.order_items; create policy order_items_self_read on public.order_items for select using(exists(select 1 from orders o where o.id=order_id and (o.user_id=auth.uid() or exists(select 1 from profiles where id=auth.uid() and role='admin'))));
drop policy if exists reviews_public_read on public.reviews; create policy reviews_public_read on public.reviews for select using(approved=true or auth.uid()=user_id or exists(select 1 from profiles where id=auth.uid() and role='admin'));
drop policy if exists reviews_user_insert on public.reviews; create policy reviews_user_insert on public.reviews for insert with check(auth.uid()=user_id);
drop policy if exists wishlist_self on public.wishlist; create policy wishlist_self on public.wishlist for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists addresses_self on public.addresses; create policy addresses_self on public.addresses for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists coupons_public_read on public.coupons; create policy coupons_public_read on public.coupons for select using(active=true);

-- Order creation is performed by the server using the service role key. Never expose that key to the browser.

drop policy if exists products_admin_write on public.products; create policy products_admin_write on public.products for all using(exists(select 1 from profiles where id=auth.uid() and role='admin')) with check(exists(select 1 from profiles where id=auth.uid() and role='admin'));
drop policy if exists orders_admin_write on public.orders; create policy orders_admin_write on public.orders for update using(exists(select 1 from profiles where id=auth.uid() and role='admin')) with check(exists(select 1 from profiles where id=auth.uid() and role='admin'));
drop policy if exists reviews_admin_write on public.reviews; create policy reviews_admin_write on public.reviews for all using(exists(select 1 from profiles where id=auth.uid() and role='admin')) with check(exists(select 1 from profiles where id=auth.uid() and role='admin'));
